name: CI

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      run: ./scripts/runSwiftFormat.sh -l

  test_macos:
    needs: run_lint

    runs-on: macos-latest

    env:
      TESTS_PRIVATEKEY: ${{ secrets.TESTS_PRIVATEKEY }}

    steps:
    - uses: actions/checkout@v4

    - name: SetupKey
      run: ./scripts/setupKey.sh "${{ secrets.TESTS_PRIVATEKEY }}"

    - name: Build
      run: swift build

    - name: Tests
      run: swift test

  test_linux:
    needs: [run_lint, test_macos]

    runs-on: ubuntu-latest

    container:
      image: swift:5.9-jammy

    env:
      TESTS_PRIVATEKEY: ${{ secrets.TESTS_PRIVATEKEY }}

    steps:
    - uses: actions/checkout@v4

    - name: SetupKey
      run: ./scripts/setupKey.sh "${{ secrets.TESTS_PRIVATEKEY }}"

    - name: Build
      run: swift build

    - name: Tests
      run: swift test
